<a href="https://colab.research.google.com/github/rajat25jain/website/blob/master/Multi_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd


In [ ]:
data_set = pd.read_csv('MLRData.csv')

In [ ]:
data_set

R&D spend      Admin  Marketing        State  Profit
0   162597.70  151377.59  443898.53   California  192262
1   153441.51  101145.55  407934.54      Florida  191792
2   144372.41  118671.85  383199.62     New York  191050
3   142107.34   91391.77  366168.42      Florida  182902
4   131876.90   99814.71  362861.36     New York  166188
5   134615.46  147198.87  127716.82   California  156991
6   130298.13  145530.06  323876.68      Florida  156123
7   120542.52  148718.95  311613.29     New York  155753
8   123334.88  108679.17  304981.62   California  152212
9   101913.08  110594.11  229160.95      Florida  149760
10  100671.96   91790.61  249744.55   California  146122
11   93863.75  127320.38  249839.44      Florida  144259
12   91992.39  135495.07  252664.93   California  141586
13  119943.24  156547.42  256512.92      Florida  134307

In [ ]:
x= data_set.iloc[:,:-1].values
y= data_set.iloc[:,4:5].values
print(x)
print(y)


[[162597.7 151377.59 443898.53 ' California']
 [153441.51 101145.55 407934.54 ' Florida']
 [144372.41 118671.85 383199.62 ' New York']
 [142107.34 91391.77 366168.42 ' Florida']
 [131876.9 99814.71 362861.36 ' New York']
 [134615.46 147198.87 127716.82 ' California']
 [130298.13 145530.06 323876.68 ' Florida']
 [120542.52 148718.95 311613.29 ' New York']
 [123334.88 108679.17 304981.62 ' California']
 [101913.08 110594.11 229160.95 ' Florida']
 [100671.96 91790.61 249744.55 ' California']
 [93863.75 127320.38 249839.44 ' Florida']
 [91992.39 135495.07 252664.93 ' California']
 [119943.24 156547.42 256512.92 ' Florida']]
[[192262]
 [191792]
 [191050]
 [182902]
 [166188]
 [156991]
 [156123]
 [155753]
 [152212]
 [149760]
 [146122]
 [144259]
 [141586]
 [134307]]


In [ ]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.compose import ColumnTransformer
labelencode_x=LabelEncoder()
x[:,3]=labelencode_x.fit_transform(x[:,3])
#We have used column transformer because categorical feature function is
#depreciated by Onehotencoder
ct= ColumnTransformer([("State",OneHotEncoder(),[3])],remainder='passthrough')
x=ct.fit_transform(x)

#avoiding dummy variable trap



In [ ]:
x=x[:,1:]

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)


In [ ]:
x_train

array([[1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [0.0, 0.0, 91992.39, 135495.07, 252664.93]], dtype=object)

In [ ]:
from sklearn.linear_model import LinearRegression
linearregression= LinearRegression()
linearregression.fit(x_train,y_train)


LinearRegression()

In [ ]:
y_pred =linearregression.predict(x_test)
y_pred

array([[168384.53486382],
       [159291.41383154],
       [183370.54135068]])

In [ ]:
print(linearregression.score(x_train,y_train))
print(linearregression.score(x_test,y_test))


0.9312368076377656
-4.451528673885332
